### ISSUE TITLE
Enable Managed Service Identity as a mechanism to access to the event hub for logging

### ISSUE THREAD

**Issue by rockydevnet** [UKHO/EventHub-Logging-Provider#36]
The connection to the event hub is currently defined as a connection string, with an access key. It would be good if we can provide a mechanism to allow configuration to use a simple connection definition without any access key, and it use the Managed Service Identity.  This would remove the requirement of the client to store/manage an access key.

**Comment by bolt-io** [comment]
Added to Calypso backlog

[Product Backlog Item 157635](https://dev.azure.com/ukhydro/Calypso/_workitems/edit/157635): Event Hub Logging Provider: Enable Managed Service Identity as a mechanism to access to the event hub for logging

**Comment by srjames-ukho** [comment]
Implemented https://github.com/UKHO/EventHub-Logging-Provider/pull/62
